Formatting pass
BuddiesOfBudgie/budgie-screensaver pull request #2
Opened 2022-01-14 20:24 UTC by serebit

Perform a formatting pass based on the `.clang-format` file in budgie-desktop.

2022-01-17 22:37 UTC, JoshStrobl requested changes
Gonna be real. I didn't review all the files, but I think there is enough patterns of regressions and from what it seems, odd column limit, to warrant changes.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver-command.c
> +		g_dbus_message_new_method_call(GS_SERVICE, GS_PATH, GS_INTERFACE, name);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver-command.c
> +		g_dbus_message_new_method_call(GS_SERVICE, GS_PATH, GS_INTERFACE, name);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver-command.c
> +			connection, message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, &error);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver-dialog.c
> +		auth_message_handler, plug, &error);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver-dialog.c
> +		NULL);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver-dialog.c
> +	}
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gnome-screensaver.c
> +		env_vars, "XDG_CURRENT_DESKTOP"); // Get the current desktop value
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-listener-dbus.h
> + * USA.
Shouldn't be on new line

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-listener-dbus.h
> +	(G_TYPE_INSTANCE_GET_CLASS((o), GS_TYPE_LISTENER, GSListenerClass))
Feel like this is a regression.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-listener-dbus.h
> +	void (*show_message)(GSListener* listener, const char* summary,
Could do with some spacing between the name and definition.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-lock-plug.h
> + * USA.
Newline should be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-lock-plug.h
> +	(G_TYPE_INSTANCE_GET_CLASS((o), GS_TYPE_LOCK_PLUG, GSLockPlugClass))
Regression

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-lock-plug.h
> +	void (*close)(GSLockPlug* plug);
Should have a space between (*response) and (GSLock...) as an example

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-manager.h
> + * USA.
Regression

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-manager.h
> +	(G_TYPE_INSTANCE_GET_CLASS((o), GS_TYPE_MANAGER, GSManagerClass))
Regression

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-manager.h
> +	void (*auth_request_end)(GSManager* manager);
See similar comments on this

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-manager.h
> +	gboolean user_switch_enabled);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-manager.h
> +	const char* body, const char* icon);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +	GSMonitor* monitor) {
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +	gboolean handled;
Newline could probably be removed or given how many args there are, break this up.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		gs_listener_get_activation_enabled(monitor->priv->listener);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +					"fade-out");
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +	GSMonitor* monitor) {
Weird newlines

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +	GSMonitor* monitor) {
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		monitor->priv->prefs->keyboard_command);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		monitor->priv->listener, monitor->priv->prefs->idle_activation_enabled);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		(!manager_active && !idle_detection_active && idle_detection_enabled);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		listener_show_message_cb, monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		G_CALLBACK(listener_show_message_cb), monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +	GSMonitor* monitor) {
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		monitor->priv->watcher, on_watcher_status_message_changed, monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		G_CALLBACK(on_watcher_status_message_changed), monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		G_CALLBACK(manager_deactivated_cb), monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		_gs_monitor_update_from_prefs, monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.c
> +		G_CALLBACK(_gs_monitor_update_from_prefs), monitor);
Newline could probably be removed.

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.h
> + * USA.
Regression

2022-01-17 22:37 UTC, JoshStrobl commented on src/gs-monitor.h
> +	(G_TYPE_INSTANCE_GET_CLASS((o), GS_TYPE_MONITOR, GSMonitorClass))
Some unnecessary newlines / breaks

2022-01-17 22:39 UTC, serebit commented
The way I did this was the following:
- Use the defaults of `clang-format` to get rid of weird constructs that I couldn't determine options for in the configuration file
- Do a second pass with the budgie-desktop defaults to align everything with our actual standards
Seems like most of the regressions are due to a column limit, so I'll redo the passes with that option set to 0. Should fix most things.

2022-01-17 23:56 UTC, serebit commented
Re-formatted with a column limit of 120 in clang-format, which auto-breaks pretty nicely.

2022-01-20 16:52 UTC, JoshStrobl requested changes
Is this where I mention that fighting against formatters isn't the most optimal use of time because they probably will never be able to be granular enough in where they should conditionally enforce certain styling, so why bother? :P

2022-01-20 16:52 UTC, JoshStrobl commented on src/gnome-screensaver.c
> +			NULL); // In the event gjs is still going after 30s, kill again
Still some needless newlines.

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-grab-x11.c
> +													: "unknown value"));
This is pretty nasty

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-grab-x11.c
> +				G_OBJECT(grab->priv->keyboard_grab_window), (gpointer*) &grab->priv->keyboard_grab_window);
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-listener-dbus.c
> +	&gs_listener_unregister_handler, &gs_listener_message_handler, NULL, NULL, NULL, NULL};
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-listener-dbus.c
> +		method_name);
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-listener-dbus.c
> +				DBUS_TYPE_INVALID)) {
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-listener-dbus.c
> +		G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);
Can't say this is an improvement to be honest

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-listener-dbus.c
> +		object_class, PROP_ACTIVE, g_param_spec_boolean("active", NULL, NULL, FALSE, G_PARAM_READWRITE));
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-listener-dbus.c
> +		object_class, PROP_ACTIVATION_ENABLED, g_param_spec_boolean("activation-enabled", NULL, NULL, TRUE, G_PARAM_READWRITE));
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-lock-plug.c
> +		object_class, PROP_SWITCH_ENABLED, g_param_spec_boolean("switch-enabled", NULL, NULL, FALSE, G_PARAM_READWRITE));
Needless newlines

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-lock-plug.c
> +		G_STRUCT_OFFSET(GSLockPlugClass, close), NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
Regression IMO

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-lock-plug.c
> +		gs_lock_plug_add_button(GS_LOCK_PLUG(plug), plug->priv->auth_action_area, _("S_witch User…"));
Needless newline

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-manager.c
> +		G_STRUCT_OFFSET(GSManagerClass, auth_request_end), NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
Regression imo

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-manager.c
> +		object_class, PROP_LOGOUT_COMMAND, g_param_spec_string("logout-command", NULL, NULL, NULL, G_PARAM_READWRITE));
Needless newlines

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-watcher-x11.c
> +		G_TYPE_BOOLEAN);
Can't say this is this is an improvement.

2022-01-20 16:52 UTC, JoshStrobl commented on src/gs-window-x11.c
> +			0, G_PARAM_READWRITE | G_PARAM_CONSTRUCT));
Signals probably have value in being broken up but the install_property calls, dunno. Especially when one like is almost entirely just the function name.

2022-01-20 17:49 UTC, serebit commented
Okay, screw this. I'll figure out a better way to apply specific rules.

2022-01-20 17:49 UTC, closed without merging